# Generated by Django 2.2.12 on 2020-04-20 01:01

import django.core.validators
from django.db import migrations, models
import mask_project.utilities
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_organization_name', models.CharField(help_text='What organization is in need of masks?', max_length=100, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Requesting Organization Name')),
                ('drop_off_address', models.CharField(help_text='Street address donated masks should be delivered to.', max_length=100, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Drop off location street address')),
                ('drop_off_city', models.CharField(help_text='City to delivered to, help people with GPS devices find you.', max_length=25, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Drop off location city')),
                ('drop_off_zip_code', models.CharField(help_text='Drop off location zip code', max_length=10, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')])),
                ('drop_off_instructions', models.TextField(help_text='Where should a person leave donated masks when they get to the drop off location?', max_length=1000, verbose_name='Drop off instructions')),
                ('drop_off_times', models.TextField(help_text='What days / times are people able to drop off masks?', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Drop off times')),
                ('shaped_masks', models.BooleanField(default=False)),
                ('rectangular_masks', models.BooleanField(default=False)),
                ('custom_pattern_url', models.URLField(blank=True, null=True, verbose_name='URL to custom pattern for needed for donation')),
                ('scrub_caps', models.BooleanField(default=False)),
                ('quantity_needed', models.CharField(help_text='How many are really needed?', max_length=30, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Quantity of item requested needed')),
                ('contact_first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Contact first name')),
                ('contact_last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\(\\)\\/\\-@_&#:,\\.\\?!\\s\\']*$"), 'Only letters, numbers, spaces and &#40;&#41;&#64;&#47;&#45;&#95;&#38;&#35;&#58;&#44;&#46;&#33;&#63; are allowed here.')], verbose_name='Contact last name')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Contact email')),
                ('contact_phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[mask_project.utilities.validate_phone_number], verbose_name='Contact phone number')),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('responded_to', models.BooleanField(default=False, help_text='For optional internal use')),
            ],
            options={
                'verbose_name_plural': 'Donation Requests',
                'db_table': 'donation_requests',
                'ordering': ['time_submitted', 'responded_to'],
            },
        ),
    ]
